config/routes.rb
Rails.application.routes.draw do
  root 'users#new'

  get "/signin" => "sessions#new", :as => :sign_in
  get "/signout" => "sessions#destroy", :as => :sign_out
  get "/signup" => "users#new", :as => :sign_up
  post "/signup" => "users#create"
  get "/dashboard" => "dashboard#show", :as => :dashboard
  get "/settings" => "users#edit", :as => :settings
  get "/install-bookmarklet" => "users#install_bookmarklet", :as => :install_bookmarklet

  resources :users, :except => [:index, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, except: [:destroy]

  resources :selections, except: [:new, :edit, :create, :update] do
    get 'create_via_bookmarklet', :action => :create_via_bookmarklet, :on => :collection
  end

  resources :web_pages
end

app/models/selection.rb
class Selection < ActiveRecord::Base
  belongs_to :user
  belongs_to :web_page
  accepts_nested_attributes_for :web_page
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :selections

  validates_presence_of :email, :password
  validates_length_of :password, :minimum => 6, :message => "must be at least 6 characters long"
  validates :email, :format => /@/
  validates_uniqueness_of :email, { case_sensitive: false }

  def self.current
    RequestStore.store[:user]
  end

  def self.current=(user)
    RequestStore.store[:user] = user
  end
end

app/models/web_page.rb
class WebPage < ActiveRecord::Base
  URI_REGEX = /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix
  validates_presence_of :uri, :message => 'is required'
  validates :uri, :format => {:with => URI_REGEX}

  def uri=(uri_string)
    set_uri_attribute(:uri, uri_string)
  end

  def icon=(icon_uri_string)
    set_uri_attribute(:icon, icon_uri_string)
    invalid_uri = (URI_REGEX =~ icon) == nil
    write_attribute :icon, nil if invalid_uri
  end



protected

  def set_uri_attribute(attr_sym, uri_string)
    unless uri_string.blank?
      unless uri_string.split(':')[0] == 'http' || uri_string.split(':')[0] == 'https'
          uri_string = "http://" + uri_string
      end
    end
    write_attribute attr_sym, uri_string
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login

  def set_current_user
    User.current = current_user
  end

  def not_authenticated
    redirect_to sign_in_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @selections = current_user.selections.order('CREATED_AT DESC')
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login
  layout 'outer_admin'

  def new
    @user = User.new
  end

  # request password reset.
  # you get here when the user entered his email in the reset password form and submitted it.
  def create
    @user = User.find_by_email!(adapted_params[:user][:email])

    # This line sends an email to the user with instructions on how to reset their password (a url with a random token)
    @user.deliver_reset_password_instructions! if @user

    # Tell the user instructions have been sent whether or not email was found.
    # This is to not leak information to attackers about which emails exist in the system.
  end

  # This is the reset password form.
  def edit
    @user = User.load_from_reset_password_token(adapted_params[:id])
    @token = adapted_params[:id]
    not_authenticated unless @user
  end

  # This action fires when the user has sent the reset password form.
  def update
    @token = adapted_params[:token]
    @user = User.load_from_reset_password_token(adapted_params[:token])
    not_authenticated unless @user
    # the next line clears the temporary token and updates the password
    if @user.change_password!(adapted_params[:user][:password])
      auto_login(@user)
      redirect_to(current_user_home_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end

  private
  def adapted_params
    params.permit(:email)
  end
end

app/controllers/selections_controller.rb
class SelectionsController < ApplicationController
  include SelectionsHelper
  skip_before_filter :require_login, :only => [:create_via_bookmarklet]
  skip_before_filter :verify_authenticity_token, only: [:create_via_bookmarklet]
  before_action :set_selection, only: [:show, :destroy]

  # GET /selections
  def index
    @selections = current_user.selections.all
  end

  # GET /selections/1
  def show
  end

  def create_via_bookmarklet
    if logged_in? == false
      render_bookmarklet(:ringo_bookmarklet, 'authenticate_for_bookmarklet')
      return
    else
      adapted_params = {
        content: params[:content],
        web_page_attributes: {
          uri: params[:uri]
        }
      }
      @selection = current_user.selections.build(adapted_params)

      if @selection.save
        render_bookmarklet(:ringo_bookmarklet, 'create_via_bookmarklet')
      else
        render_bookmarklet(:ringo_bookmarklet, 'failed_to_create_via_bookmarklet')
      end
    end
  end

  # DELETE /selections/1
  def destroy
    @selection.destroy
    respond_to do |format|
      format.js
      format.html {
        redirect_to selections_url, notice: 'Selection was successfully destroyed.'
      }
    end
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_selection
    @selection = Selection.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login
  layout 'outer_admin'

  def new
    @user = User.new
  end

  def create
    respond_to do |format|
      if @user = login(adapted_params[:email].downcase, adapted_params[:password], remember_me=true)
        format.json { render json: @user, :status => :ok }
        format.html { redirect_back_or_to(dashboard_path) }
      else
        error_msg = "Login failed. Please try again."
        format.json { render :json => {error: error_msg}, :status => :unprocessable_entity }
        format.html { flash.now['danger'] = error_msg; render :action => "new" }
      end
    end
  end

  def destroy
    logout
    redirect_to sign_in_path
  end

private
  def adapted_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:new, :create]

  def new
    return redirect_to dashboard_path if current_user
    @user = User.new
    render :new, layout: 'outer_admin'
  end

  def create
    @user = User.new({email: adapted_params[:email].downcase, password: adapted_params[:password]})

    respond_to do |format|
      if @user.save
        auto_login(@user, true)

        format.json { render :json, status: :ok }
        format.html { redirect_to dashboard_path }
      else
        format.json { render :json => {error: "invalid username-password combination."}, :status => :unprocessable_entity }
        format.html { render 'new', layout: 'outer_admin' }
      end
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find_by_id!(params[:id])

    respond_to do |format|
      if @user.update_attributes(adapted_params)
        format.html { flash.now['success'] = 'Updated settings.'; render :edit }
      else
        format.html { flash.now['danger'] = "Encountered an error in updating."; render :edit }
      end
    end
  end

private
  def adapted_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/web_pages_controller.rb
class WebPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(title)
    content_for :title, title
    content_tag :title, title
  end

  def page_header_title(title)
    content_for :page_header_title, title
  end
end

app/helpers/selections_helper.rb
module SelectionsHelper
  include RailsBookmarklet
end

app/helpers/web_pages_helper.rb
module WebPagesHelper
end

app/views/dashboard/_welcome.html.erb
<%= page_title('➜ Ringo') %>
<%= page_header_title 'Welcome to Ringo!' %>

<div class="visible-lg">
  <div class="col-md-8">
    <div>
      To get started, drag the Ringo bookmarklet below to the bookmarks bar in your browser.
    </div>
    <br />

    <div class="col-md-3 well" style="text-align: center">
      <a class="btn btn-small" href="<%= RailsBookmarklet.compile_invocation_script(create_via_bookmarklet_selections_url, {
        :error => 'Uh-oh, something went wrong.',
        :params => {
          "uri" => "'+encodeURIComponent(d.location)+'"
        }
      }) %>">➜ Ringo</a>
    </div>

    <div style="clear: both">
      Then, whenever you want to save a quote to Ringo, select it and click the <span class="btn btn-small">➜ Ringo</span> button in your bookmarks bar, and it will be saved to your Ringo account.
    </div>

  </div>
</div>

<div class="hidden-lg">
  <p>
    The Ringo bookmarklet saves whatever text you have highlighted to Ringo. Follow the directions below to get started!
  </p>

  <ol>
    <li>
      Tap on the field below and press down until some text is selected in a blue overlay. Adjust this blue overlay to cover all the code in the field, then click 'Copy'.
      <br />
      <p class="well" style="word-wrap: break-word"><%= RailsBookmarklet.compile_invocation_script(create_via_bookmarklet_selections_url, {
        :error => 'Uh-oh, something went wrong.',
        :params => {
          "uri" => "'+encodeURIComponent(d.location)+'"
        }
      }) %>
      </p>
    </li>
    <li>Bookmark this page.</li>
    <li>Open your bookmarks by clicking the book button at the bottom of your browser.</li>
    <li>Click the 'Edit' button on the lower left.</li>
    <li>Click on the '➜ Ringo' bookmark.</li>
    <li>Click on the field that starts with 'http://ringo4writers.com/'.</li>
    <li>Click the circled 'x' at the right end of that field to clear it.</li>
    <li>Hold down on this field until you see the 'Paste' button.</li>
    <li>Click 'Paste'.</li>
    <li>Click the 'Done' button on the lower right.</li>
    <li>Click the 'Done' button on the lower left.</li>
    <li>Click the 'Done' button on the upper right.</li>
  </ol>

  <p>Now, whenever you want to save some text to Ringo, select it and click the book button at the bottom of your browser, then click the <br />'➜ Ringo' bookmark, and it will be saved to your Ringo account.</p>
</div>

app/views/dashboard/show.html.erb
<% template = @selections.empty? ? 'welcome' : 'selections/index' %>
<%= render template %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <head>
        <title>Ringo</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <link rel="shortcut icon" href="/favicon.ico">
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <link href='//fonts.googleapis.com/css?family=Josefin+Slab:100,300|Allura|Open+Sans:300,400' rel='stylesheet' type='text/css'>
    </head>
    <body>
      <div id="outer-wrapper" class="row col-md-10 col-md-offset-1">
        <header>
          <nav class="navbar navbar-default">

            <!-- application logo -->
            <%= link_to dashboard_path, class: 'navbar-brand' do %>
              <!-- application logo visible on large screens -->
              <h1 id="ringo-brand">Ringo</h1>
              <!-- application logo visible on small screens -->
              <h1 id="ringo-brand" class="logo-xs">Ringo</h1>
            <% end %>

            <!-- dropdowns -->
            <ul class="nav">

              <!-- light dropdown -->
              <li class="dropdown light only-icon">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <!-- ... -->
                </a>
                <!-- ... -->
              </li>

              <!-- medium dropdown & widget -->
              <li class="dropdown medium only-icon widget">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <!-- ... -->
                </a>
                <!-- ... -->
              </li>

              <!-- dark dropdown & user menu -->
              <li class="dropdown dark user-menu">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <span class="user-name"><i class="icon-user"></i> <%= current_user.email %></span>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to settings_path do %>
                      <i class="icon-cog"></i> Settings
                    <% end %>
                  </li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to sign_out_path do %>
                      <i class="icon-signout"></i> Sign out
                    <% end %>
                </ul>
              </li>
            </ul>

          </nav>
        </header>

        <div id="wrapper">
          <section id="content">
            <div id="main-container" class="container">
              <div class="row" id="content-wrapper">
                <div class="col-xs-12">

                  <!-- page header container -->
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="page-header">
                        <h1 class="pull-left">
                          <% if content_for? :page_header_title %>
                            <i class="icon-th"></i>
                            <span>
                              <%= yield :page_header_title %>
                            </span>
                          <% elsif content_for? :breadcrumb %>
                            <%= yield :breadcrumb %>
                          <% end %>
                        </h1>
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-sm-12">
                      <%= yield %>
                    </div>
                  </div>

                </div>
              </div>

            </div>
          </section>
        </div>
      </div>

      <%= yield :scripts %>

      <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
      <script>
          (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
          function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
          e=o.createElement(i);r=o.getElementsByTagName(i)[0];
          e.src='//www.google-analytics.com/analytics.js';
          r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
          ga('create','UA-XXXXX-X');ga('send','pageview');
      </script>
    </body>
</html>

app/views/layouts/outer_admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ringo</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="shortcut icon" href="/favicon.ico">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <link href='//fonts.googleapis.com/css?family=Josefin+Slab:100,300|Allura|Open+Sans:300,400' rel='stylesheet' type='text/css'>
  </head>
  <body class='login contrast-background'>
    <div class='middle-container'>
      <div class='middle-row'>
        <div class='middle-wrapper'>
          <div class='login-container-header'>
            <div class='container'>
              <div class='row'>
                <div class='col-sm-12'>
                  <div class='text-center'>
                    <h1 id="ringo-homepage-brand">Ringo</h1>
                    <h2 id="subtitle">for writers</h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/selections/_index.html.erb
<%= content_for :page_header_title do %>
  Quotes
  <button id="copy-all" class="btn" title='Copy all quotes to clipboard.'>
    <i class="icon-copy"></i> Copy all quotes to clipboard
  </button>
<% end %>

<div class="row">
  <div class="col-sm-12">
    <table class="table">
      <thead>
        <tr>
          <th>
            Content
          </th>
          <th>
            Saved
          </th>
          <th id="actions-header"></th>
        </tr>
      </thead>
      <tbody id="quotes">
        <% @selections.each do |selection| %>
          <tr>
            <td>
              <p id="selection-<%= selection.id %>" class="selection-content">&ldquo;<%= selection.content %>&rdquo;</p>
              <%= link_to selection.web_page.uri, selection.web_page.uri, class: 'selection-uri', target: '_blank' %></td>
            </td>
            <td class='selection-saved-at'>
              <%= selection.created_at.in_time_zone.strftime('%_m/%d/%y') %>
              <br />
              <%= selection.created_at.in_time_zone.strftime('%l:%M%P') %>
            </td>

            <td>
              <div class="text-right">
                <button class="btn btn-xs copy-to-clipboard" data-clipboard-target='selection-<%= selection.id %>' title='Copy quote to clipboard.'>
                  <i class="icon-copy"></i> Copy
                </button>

                <%= link_to selection, method: :delete, remote: true, data: { confirm: 'Delete this quote?' }, class: 'btn btn-danger btn-xs' do %>
                  <i class="icon-remove"></i>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>

<% content_for :scripts do %>
<script>
  $(document).ready(function() {
    new ZeroClipboard($('.copy-to-clipboard'));

    var $copyAll = $('#copy-all'),
        allQuotes = '';
    $('#quotes tr').each(function(i, el) {
      var $el = $(el),
          quote = $el.find('.selection-content').text(),
          uri = $el.find('.selection-uri').text(),
          savedAt = $el.find('.selection-saved-at').text(),
          CR = String.fromCharCode(13),
          allTogether = quote + CR + uri + CR + savedAt + CR + CR;

      allQuotes = allQuotes + allTogether;
    });

    $copyAll.attr('data-clipboard-text', allQuotes);
    new ZeroClipboard($copyAll);
  });
</script>
<% end %>

app/views/selections/authenticate_for_bookmarklet.html.erb
<%= bookmarklet_stylesheet_link_tag "bookmarklet" %>

<p id="ringo-bookmarklet-message">
  <span>
    <a href="<%= sign_in_url %>" target="_blank" onclick="document.querySelector('#ringo_bookmarklet_container').remove();">
      Please log in to Ringo.
    </a>
  </span>
</p>

app/views/selections/create_via_bookmarklet.html.erb
<%= bookmarklet_stylesheet_link_tag "bookmarklet" %>

<p id="ringo-bookmarklet-message">
  <span>
    <span id="ringo-bookmarklet-message-content"> Saving to Ringo...</span>
  </span>
</p>

<script type="text/javascript">
  (function() {
    var uri = '<%= @uri %>',
        selection = window.getSelection ? window.getSelection().toString() : document.selection.createRange().text,
        params = "uri="+uri+"&content="+selection,
        baseUrl = "<%= persist_via_bookmarklet_selections_url %>",
        requestUrl = baseUrl + '?' + params;
    if (!selection) {
      document.location = '<%= root_url %>';
    } else {
      ringo_bookmarklet.support.load_script(requestUrl, function() {
        // script loaded
      });
    }
  })();
</script>

app/views/selections/destroy.js.erb
$("#selection-<%= @selection.id %>").closest('tr').fadeOut('slow');

app/views/selections/failed_to_create_via_bookmarklet.html.erb
<%= bookmarklet_stylesheet_link_tag "bookmarklet" %>

<p id="ringo-bookmarklet-message">
  <span>
    <span id="ringo-bookmarklet-message-content">Sorry, can't save this selection. Please try again later.</span>
  </span>
</p>

<script type="text/javascript">
  (function() {
    var hide = function() {
      var el = document.querySelector('#ringo_bookmarklet_container');
      el.classList.add('hidden');
      setTimeout(function() {
        el.remove();
      }, 3000);
    };
    setTimeout(hide, 10000);
  })();
</script>

app/views/selections/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_selection_path(@selection) %> |
<%= link_to 'Back', selections_path %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :p, msg, :class => "alert alert-#{name}" %>
<% end %>

app/views/shared/_sign_up_footer.html.erb
<div class='login-container-footer'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-12'>
        <div class='text-center'>
          <a href='<%= sign_up_path %>'>
            <i class='icon-user'></i>
            New to Ringo?
            <strong>Sign up</strong>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_install_bookmarklet.html.erb
<%= page_title('➜ Ringo') %>

<div id="am-main">
  <ul id="am-settings-nav" class="nav nav-tabs">
    <li><a href="/settings">Settings</a></li>
    <li class="active"><a href="#">Install Bookmarklet</a><li>
  </ul>
  <%= render partial: 'install_bookmarklet_copy' %>
</div>

app/views/users/_install_bookmarklet_copy.html.erb
<div class="visible-lg">
  <div class="col-md-8">
    <div>
      Drag the Ringo bookmarklet below to the bookmarks bar in your browser.
    </div>
    <br />

    <div class="col-md-3 well" style="text-align: center">
      <a class="btn btn-small" href="<%= RailsBookmarklet.compile_invocation_script(create_via_bookmarklet_selections_url(protocol: 'https'), {
        :error => 'Uh-oh, something went wrong.',
        :params => {
          "uri" => "'+encodeURIComponent(d.location)+'",
          "content" => "'+s+'"
        }
      }) %>">➜ Ringo</a>
    </div>

    <div style="clear: both">
      Then, whenever you want to save some text to Ringo, select it and click the <span class="btn btn-small">➜ Ringo</span> button in your bookmarks bar, and it will be saved to your Ringo account. If you don't have any text selected, clicking the <span class="btn btn-small">➜ Ringo</span> button will just take you back to Ringo.
    </div>

  </div>
</div>

<div class="hidden-lg">
  <p>
    The Ringo bookmarklet saves whatever text you have highlighted to Ringo. Follow the directions below to install the bookmarklet.
  </p>

  <ol>
    <li>
      Tap on the field below and press down until some text is selected in a blue overlay. Adjust this blue overlay to cover all the code in the field, then click 'Copy'.
      <br />
      <p class="well" style="word-wrap: break-word"><%= RailsBookmarklet.compile_invocation_script(create_via_bookmarklet_selections_url, {
        :error => 'Uh-oh, something went wrong.',
        :params => {
          "uri" => "'+encodeURIComponent(d.location)+'"
        }
      }) %>
      </p>
    </li>
    <li>Bookmark this page.</li>
    <li>Open your bookmarks by clicking the book button at the bottom of your browser.</li>
    <li>Click the 'Edit' button on the lower left.</li>
    <li>Click on the '➜ Ringo' bookmark.</li>
    <li>Click on the field that starts with 'http://ringo4writers.com/'.</li>
    <li>Click the circled 'x' at the right end of that field to clear it.</li>
    <li>Hold down on this field until you see the 'Paste' button.</li>
    <li>Click 'Paste'.</li>
    <li>Click the 'Done' button on the lower right.</li>
    <li>Click the 'Done' button on the lower left.</li>
    <li>Click the 'Done' button on the upper right.</li>
  </ol>

  <p>Now, whenever you want to save some text to Ringo, select it and click the book button at the bottom of your browser, then click the <br />'➜ Ringo' bookmark, and it will be saved to your Ringo account.</p>
</div>

app/views/users/edit.html.erb
<%= page_header_title 'Settings' %>

<%= render partial: 'shared/flash_messages' %>

<div class="row">
  <div class='tabbable'>
    <ul class='nav nav-responsive nav-tabs'>
      <li class='active'>
        <a data-toggle='tab' href='#general'>
          General
        </a>
      </li>
      <li>
        <a href='<%= install_bookmarklet_path %>'>
          Install Bookmarklet
        </a>
      </li>
    </ul>

    <div class="tab-content">
      <div id="general" class="tab-pane active col-sm-5">
        <%= form_for(@user, html: {method: 'put', novalidate: 'novalidate', class: 'form validate-form'}) do |f| %>

          <% email_errors = @user.errors.messages[:email] %>
          <div class="form-group <%= 'has-error' if email_errors.present? %>">
            <%= f.label :email %>
            <div class="controls">
              <%= f.text_field :email, 'data-rule-required' => true, 'data-rule-email' => true, 'class' => 'form-control', 'type' => 'email' %>
            </div>
            <% email_errors and email_errors.each do |error_msg| %>
              <span class="help-block has-error"><%= error_msg %></span>
            <% end %>
          </div>

          <% password_errors = @user.errors.messages[:password] %>
          <div class="form-group <%= 'has-error' if password_errors.present? %>">
            <%= f.label :password, 'New Password' %>
            <div class="controls">
              <%= f.password_field :password, 'data-rule-minlength' => '6', 'class' => 'form-control' %>
            </div>
            <% password_errors and password_errors.each do |error_msg| %>
              <span class="help-block has-error"><%= error_msg %></span>
            <% end %>
          </div>

          <%= f.submit "Update", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/install_bookmarklet.html.erb
<%= page_header_title 'Settings' %>
<%= render partial: 'install_bookmarklet' %>

app/views/users/new.html.erb
<%= page_title 'Sign up' %>

<div class='login-container'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-4 col-sm-offset-4'>
        <p id="pitch">Ringo makes it simple to clip quotes from web pages and add them to your writing.</p>
        <br />

        <%= render partial: 'shared/flash_messages' %>

        <%= form_for(@user, url: users_path, html: {novalidate: 'novalidate', class: 'form validate-form'}) do |f| %>

            <% email_errors = @user.errors.messages[:email] %>
            <div class="form-group <%= 'has-error' if email_errors.present? %>">
              <div class="controls with-icon-over-input">
                <%= f.text_field :email, 'data-rule-required' => true, 'data-rule-email' => true, 'class' => 'form-control', 'Placeholder' => 'E-mail', 'type' => 'email' %>
                <i class='icon-user text-muted'></i>
              </div>
              <% email_errors and email_errors.each do |error_msg| %>
                <span class="help-block has-error"><%= error_msg %></span>
              <% end %>
            </div>

            <% password_errors = @user.errors.messages[:password] %>
            <div class="form-group <%= 'has-error' if password_errors.present? %>">
              <div class="controls with-icon-over-input">
                <%= f.password_field :password, 'data-rule-required' => true, 'data-rule-minlength' => '6', 'class' => 'form-control', 'Placeholder' => 'Password' %>
                <i class='icon-lock text-muted'></i>
              </div>
              <% password_errors and password_errors.each do |error_msg| %>
                <span class="help-block has-error"><%= error_msg %></span>
              <% end %>
            </div>

            <%= f.submit "Sign up", class: 'btn btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class='login-container-footer'>
  <div class='container'>
    <div class='row'>
      <div class='col-sm-12'>
        <div class='text-center'>
          <a href='<%= sign_in_path %>'>
            <i class='icon-user'></i>
            Sign in
          </a>
        </div>
      </div>
    </div>
  </div>
</div>